name: TP Tfsec

on:
   workflow_dispatch:

jobs:
  tfsec:
    name: Run tfsec sarif report
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run tfsec
        uses: aquasecurity/tfsec-action@v1.0.0

